services:
  movies:
    build: bochumounika/movies
    image: movies:v1
    ports:
      - "81:80"

  dth:
    build: bochumounika/dth
    image: dth:v1
    ports:
      - "82:80"

  recharge:
    build: bochumounika/recharge
    image: recharge:v1
    ports:
      - "83:80"

  train:
    build: bochumounika/train
    image: train:v1
    ports:
      - "84:80"
